=== edockter/CIT-41200-XML/Assignment 11/account.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
   CIT 41200
   Assignment 12   
   
   Author:   Eric Dockter
   Date:     12/01/2016
   
   Filename:         account.xsd
   Supporting Files: account.xml
--> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://www.engr.iupui.edu/~efernand/account" 
    targetNamespace="http://www.engr.iupui.edu/~efernand/account"    
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" >
    
    <xs:element name="account">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="owner" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first" />
                                        <xs:element name="last" />                                        
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>                            
                            <xs:element name="address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="street" />
                                        <xs:element name="city" />
                                        <xs:element name="state" />
                                        <xs:element name="zip" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>                            
                        </xs:sequence>
                    </xs:complexType>                    
                </xs:element>  
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="deposit">
                        <xs:complexType >            
                            <xs:sequence>
                                <xs:element name="from" type="fromType" />
                                <xs:element ref="amount" />
                                <xs:element ref="date" />
                                <xs:element ref="description" minOccurs="0" />
                            </xs:sequence>
                            <xs:attribute name="type" type="typeType"/>            
                        </xs:complexType>        
                    </xs:element>                    
                    <xs:element name="payment" >
                        <xs:complexType>            
                            <xs:sequence>
                                <xs:element name="to" type="fromType" />
                                <xs:element ref="amount" />
                                <xs:element ref="date" />
                                <xs:element ref="description" minOccurs="0" />
                            </xs:sequence>
                            <xs:attribute name="type" type="typeType"/>
                            <xs:attribute name="checknum" type="checknumType"/>
                        </xs:complexType>        
                    </xs:element>      
                </xs:choice>                
            </xs:sequence>            
            <xs:attribute name="type" type="typeType" />
            <xs:attribute name="number" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="amount" type="amountType" />
    <xs:element name="date" type="dateType" />
    <xs:element name="description" type="xs:string" />
    
    <xs:simpleType name="categoryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="income" />
            <xs:enumeration value="other" />
            <xs:enumeration value="utilities" />
            <xs:enumeration value="cash" />
            <xs:enumeration value="clothing" />
            <xs:enumeration value="food" />
            <xs:enumeration value="savings" />
            <xs:enumeration value="entertainment" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="typeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="direct" />
            <xs:enumeration value="checking" />
            <xs:enumeration value="check" />
            <xs:enumeration value="cash" />
            <xs:enumeration value="transfer" />
            <xs:enumeration value="atm" />            
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="stateType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]{2}" />            
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="checknumType">
        <xs:restriction base="xs:string">
            <xs:pattern value="C\d{1,4}" />            
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dateType">
        <xs:restriction base="xs:date"/>        
    </xs:simpleType>   
    <xs:simpleType name="amountType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0" />
            <xs:fractionDigits value="2" />             
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="fromType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="category" type="categoryType" />
            </xs:extension>
        </xs:simpleContent>                
    </xs:complexType>
    
</xs:schema>

=== edockter/CIT-41200-XML/Assignment 11/account.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<account xmlns="http://www.engr.iupui.edu/~efernand/account" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="account.xsd" type="checking" number="C22233475" >
   <owner>
      <name>
         <first>Ashley</first>
         <last>Wilkes</last>
      </name>
      <address>
         <street>321 Ashburn</street>
         <city>Jasper</city>
         <state>MN</state>
         <zip>89831</zip>
      </address>
   </owner>
   <deposit type="direct">
      <from  category="income">Net World</from>
      <amount>1240.50</amount>
      <date>2005-08-24</date>
      <description>Paycheck</description>
   </deposit>

   <payment type="check" checknum="C1210">
      <to category="other">Hank's Hardware</to>
      <amount>29.15</amount>
      <date>2005-08-24</date>
      <description>Drill kit</description>
   </payment>

   <payment type="check" checknum="C1211">
      <to category="food">Food Mart</to>
      <amount>149.51</amount>
      <date>2005-08-25</date>
   </payment>

   <payment type="check" checknum="C1212">
      <to category="other">Citgo</to>
      <amount>22.50</amount>
      <date>2005-08-25</date>
      <description>Gasoline</description>
   </payment>

   <payment type="check" checknum="C1213">
      <to category="food">Pizza Now</to>
      <amount>33.24</amount>
      <date>2005-08-28</date>
      <description>Dinner</description>
   </payment>

   <deposit type="cash">
      <from category="cash">cash</from>
      <amount>200</amount>
      <date>2005-08-29</date>
   </deposit>

   <payment type="transfer" >
      <to category="utilities">Central Electric</to>
      <amount>94.85</amount>
      <date>2005-08-29</date>
      <description>Electric Bill</description>
   </payment>

   <payment type="atm">
      <to category="cash">cash</to>
      <amount>200</amount>
      <date>2005-08-20</date>
   </payment>

   <payment type="check" checknum="C1215">
      <to category="clothing">L.S.Ayres</to>
      <amount>172.50</amount>
      <date>2005-08-30</date>
      <description>New pants, shirt</description>
   </payment>

   <payment type="check" checknum="C1216">
      <to category="food">Food Mart</to>
      <amount>89.11</amount>
      <date>2005-08-30</date>
      <description>Groceries</description>
   </payment>

   <deposit type="transfer">
      <from category="savings">Saving Account</from>
      <amount>300</amount>
      <date>2005-09-01</date>
   </deposit>

   <payment type="check" checknum="C1217">
      <to category="entertainment">Ticket Source</to>
      <amount>115.95</amount>
      <date>2005-09-03</date>
      <description>Tickets for the Jazz Concert</description>
   </payment>
</account>
